### PR TITLE
OP-450 fix getDaysBetweenDate() and parseDate()

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-450.

In addition did a few other small cleanups:

- Format the file
- Use character type for single length string
- Remove unused import
- Remove unused main routine now covered by tests
- Add private constructor given all methods are static
- Use base **Calendar** class instead of **GregorianCalendar** class
- Extract common date pattern to class constant
- Given the TimeTools file is fixed via OP-450, remove the `@Ignore` directives in the test file

### CODE REVIEW

**Review by emecas — APPROVED** [review]
LGTM

```
Results :

Tests run: 1953, Failures: 0, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:31 min
[INFO] Finished at: 2021-02-24T18:35:59-06:00
[INFO] ------------------------------------------------------------------------
```

**Comment by emecas** [comment]
@dbmalkovsky  @mwithi 

I am not sure if this is related to recent changes, but while building locally I got the limpression that the volume of exceptions during maven build that you can see passing in the log has increased dramatically. 

I have reviewed the logs realted to the checks for this particular PR (https://github.com/informatici/openhospital-core/pull/339/checks) and that is observable here as well, also many messages like these:

```
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.mechanic
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.business
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.janitorial
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.mining
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.engineering
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.hospital
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.insertsecondname
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.unknown
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.other
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.farming
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.construction
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.medicine
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.foodhospitality
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.homemaker
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.mechanic
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.business
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.janitorial
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.mining
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.patient.profession.engineering
[24/Feb/2021 17:39:28] [:] ERROR - >> key not found: angal.hospital
```

any thoughts?

**Comment by dbmalkovsky** [comment]
The reason for all those keys not being found is (1) resource message bundles are not available in the Core repo and (2) I added tests to exercise `getProfessionList()` in `org.isf.patient.manager.PatientBrowserManager` recently which builds a map of all professions.   Until resource bundle handling is changed (like moving them all to Core) and split between Core and GUI there is nothing to do.

**Comment by mwithi** [comment]
> The reason for all those keys not being found is (1) resource message bundles are not available in the Core repo and (2) I added tests to exercise `getProfessionList()` in `org.isf.patient.manager.PatientBrowserManager` recently which builds a map of all professions. Until resource bundle handling is changed (like moving them all to Core) and split between Core and GUI there is nothing to do.

I confirm, as I was pointing out [here](https://github.com/informatici/openhospital-core/pull/240#issuecomment-768968148). We have to think a solution for OP-291

**Comment by mwithi** [comment]
OK also for me
```
Results :

Tests run: 1953, Failures: 0, Errors: 0, Skipped: 5
```

**Pull request merged**
