### PR TITLE
OP-1156 Update demo data with consistent age across all tables

### PR DESCRIPTION
**Pull request by mwithi**
See OP-1156

- [x] Also update CREATED_BY and CREATED_DATE fields

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
@mwithi too many changes for the git web interface; I will review locally tomorrow.

**Review by dbmalkovsky — COMMENTED** [review]
@mwithi too many changes for the git web interface; I will review locally tomorrow.

**Comment by mwithi** [comment]
> @mwithi too many changes for the git web interface; I will review locally tomorrow.

Yeah, I've noticed that... maybe is because now we have full INSERT statements... 🤦‍♂️
Anyway, with OP-1111 the file will be shorter for sure

**Review by dbmalkovsky — COMMENTED** [review]
There is nothing to review here because the telemetry commit changed the file too.  Note only the time is now different.   Guess this can be closed.

**Comment by mwithi** [comment]
> There is nothing to review here because the telemetry commit changed the file too. Note only the time is now different. Guess this can be closed.

ouch... that's true! Thanks!

**Comment by mwithi** [comment]
closed with #694

**Pull request closed without merging**
