### PR TITLE
Chore: add missing Override annotation

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Found with IntelliJ Analyze

### CODE REVIEW

**Review by mwithi — APPROVED** [review]
LGTM. BTW maybe this method could be just removed since it doesn't add anything in respect Jpa... but we can keep the class (to be renamed `PricesListIoOperationRepository`) for simmetry with the rest of the code, wdyt?

**Comment by dbmalkovsky** [comment]
How about this refactoring?

**Comment by mwithi** [comment]
> How about this refactoring?

LGTM. So we keep the `deleteById` method?

**Comment by dbmalkovsky** [comment]
For the time being until I am convinced it isn't needed 😄

**Comment by mwithi** [comment]
> For the time being until I am convinced it isn't needed 😄

it should not, but in case I feel I would keep the class for simmetry... so let's keep all of it

**Pull request merged**
