### PR TITLE
[OP-229] OPD patient search fix

### PR DESCRIPTION
**Pull request by tomek39856**

### CODE REVIEW

**Review by mwithi — CHANGES_REQUESTED** [review]
that might be something wrong, searchin "al":
image

Searching "pas" (it is shown within previous results) returns empty:
image

Even with case "Pas":
image

**Comment by tomek39856** [comment]
did you rebuild with my change? Your examples looks exactly like missing % at the end which I fixed, I'm testing it now and it's working for examples you provided

**Comment by mwithi** [comment]
> did you rebuild with my change? Your examples looks exactly like missing % at the end which I fixed, I'm testing it now and it's working for examples you provided

yeah, now I tried again and it works... it was working partially because before the list was always empty with any keyword

**Review by mwithi — APPROVED** [review]
Tested

**Pull request merged**
