### PR TITLE
Chore: misc cleanup/improvements

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Miscellaneous  cleanups, improvements, performance changes including:

- standardized the formatting of the file
- use logging instead of System.println
- remove unnecessary casting
- use primitive types instead of objects were possible
- use faster system array copy method instead of looping
- remove commented out code that wasn't used  (or will be used)

### CODE REVIEW

**Comment by mwithi** [comment]
Is this PR meant to involve only one file? In other words, is it ready to be reviewed (and merged)?

**Comment by dbmalkovsky** [comment]
Yes it is a single file.   It just had *lots* of little changes so I enumerated them so I hoped it would make looking at the diff easier.   I guess it didn't ☹️ 

Yes it is ready to be reviewed and merged.

**Comment by mwithi** [comment]
> Yes it is a single file. It just had _lots_ of little changes so I enumerated them so I hoped it would make looking at the diff easier. I guess it didn't ☹️

lol I was asking just to be sure that was not a WIP.

**Review by mwithi — APPROVED** [review]
Thanks!

**Pull request merged**
