### PR TITLE
OP-1352 Catch malformed json and don't block the application execution

### PR DESCRIPTION
**Pull request by mwithi**
See OP-1352.

### CODE REVIEW

**Review by dbmalkovsky — DISMISSED** [review]
LGTM

**Comment by mwithi** [comment]
> LGTM

wait, need to fix tests 😅

**Comment by mwithi** [comment]
> > LGTM
> 
> wait, need to fix tests 😅

Trying to mock the HTTP request and the static configuration classes, not easy, it will take time

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Pull request merged**
