### PR TITLE
OP-1301-fix-units-packets-management-in-main-store

### PR DESCRIPTION
**Pull request by mwithi**
See OP-1301.

- [x] Add new exception for cases when ordered discharging quantity is greater than the one available in the main store for the specified medical
- [x] [Fix one test that by the name was supposed to fail indeed and the new introduced check brought it to surface

### CODE REVIEW

**Review by dbmalkovsky — DISMISSED** [review]
LGTM (assuming the tests get fixed)

Just wondering if the Log statements should be left in for the system admin to help track down the problem.

**Comment by mwithi** [comment]
> LGTM (assuming the tests get fixed)
> 
> Just wondering if the Log statements should be left in for the system admin to help track down the problem.

Yes I was wondering too, let me adjust

**Comment by mwithi** [comment]
going to fix tests...

**Review by dbmalkovsky — DISMISSED** [review]
LGTM

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Pull request merged**
