### PR TITLE
OP-381 increase coverage for dlvrestype and dlvrtype packages

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Add tests to increase coverage and formatter `Manager` files to match standards.

Coverage before:
image

Coverage after:
image

All tests pass locally.

### CODE REVIEW

**Review by emecas — APPROVED** [review]
LGTM

Thank you @dbmalkovsky

**Comment by emecas** [comment]
This is not a  blocking comment to merge this PR, but I noticed that the way Eclipse measures coverage is more precise than IntelliJ, and this is why:

image

This is the portion of code for the 2 missed instructions in `org.isf.dlvrtype.service.DeliveryTypeIoOperation`  because them are being evaluate in different way, since Eclipse considers coverage separately for all possible paths, for this particular cases (lines 67 & 85) , the cases for `true` and `false`:

image

**Comment by dbmalkovsky** [comment]
@emecas  Please see the comments in [OP-391](https://openhospital.atlassian.net/browse/OP-391) where I discuss why I believe the value will never be null.   The `save()` routine returns an object or throws an exception.

**Comment by emecas** [comment]
> 
> 
> @emecas Please see the comments in [OP-391](https://openhospital.atlassian.net/browse/OP-391) where I discuss why I believe the value will never be null. The `save()` routine returns an object or throws an exception.

@dbmalkovsky I just wanted to bring here the subject about differences on coverage measures reported in each IDE, I guess I did not use the ideal lines to exemplify it.

I'm mostly agree about the particular case for OP-391, but also it is true that we can write unit tests mocking the repositories methods in order to return and test all the potential expected values (true, false, null, exception). You work has been exceptional for the scope. We can handle this subject and related somewhere else.

**Pull request merged**
