### PR TITLE
OP-1130 improve JPA methods - anamnesis package

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-1130

Changes for anamnesis package

No changes needed in GUI or API

### CODE REVIEW

**Review by mwithi — COMMENTED** [review]
Aim of the OP-1130 is only to change service layer or also to propagate changes to the above stack up to gui? In the latter case we should change also manager and so api and gui could be affected then

**Comment by dbmalkovsky** [comment]
The API code doesn't use the `PatientHistoryManager` class.

The GUI code doesn't seem to have any use for the returned object for save or update methods.

There is nothing else to change at the current time.

**Comment by mwithi** [comment]
> The API code doesn't use the `PatientHistoryManager` class.
> 
> The GUI code doesn't seem to have any use for the returned object for save or update methods.
> 
> There is nothing else to change at the current time.

Yes, I agree with current changes

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
