### PR TITLE
Chore: use more natural assertj syntax

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Minor changes to use consistent and more natural **assertj** syntax across the tests.   Some of this style was adopted with the later tests and this PR goes back and makes the style consistent.

### CODE REVIEW

**Review by emecas — COMMENTED** [review]
@dbmalkovsky  as I mentioned before knowing that there is a  `.isNotNull()` assertion available I find `.isNotEqualTo(null)` totally against the concept of natural , what do you think?

**Comment by dbmalkovsky** [comment]
Changed to use `notEquals()'.

This actually opens up to another question that I've had given that the `equals()` and `hashCode()` methods are all over the place in their implementation; why we don't settle on one of the following that can be automatically generated by the IDE:

- Equals/HashCodeBuilder from Apache commons-lang
- Equals/HashCodeBuilder from Apache commons-lang 3
- Objects.equal and hashCode from Guava
- java.util.Objects.equals and HashCode from Java7+
- IntelliJ default  (the one I like even if it is long)

It will still require a decision as to define what fields to include in `equals()` and `hashCode()` for each object.  To start we can use the the fields that are currently used.

**Comment by mwithi** [comment]
@dbmalkovsky I remember this question...

> It will still require a decision as to define what fields to include in `equals()` and `hashCode()` for each object. To start we can use the the fields that are currently used.

I think this is the main reason why we cannot change them just straight away and we must verify case by case... the only thing we could verify at this moment is if for each model, we have that `equals()` and `hashCode()` are consistent each other (`obj1.equals(obj2) = true => obj1.hashCode() == obj2.hashCode()`). Any helper tool for this?

**Comment by mwithi** [comment]
> Changed to use `notEquals()'.

You mean `notNull()`?

**Comment by dbmalkovsky** [comment]
@mwithi Yes ... too many projects .... too much code ... too little time 😄

**Review by mwithi — COMMENTED** [review]
I have 1 error:
```
Results :

Tests in error:
  initializationError(org.isf.priceslist.test.Tests): LTestPriceList;

Tests run: 1921, Failures: 0, Errors: 1, Skipped: 5
```

**Comment by dbmalkovsky** [comment]
The CI build and my local build are clean when I run `mvn clean test`

Results :

Tests run: 1953, Failures: 0, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.177 s
[INFO] Finished at: 2021-03-17T19:02:59-04:00
[INFO] ------------------------------------------------------------------------

what test is failing for you?

**Review by emecas — APPROVED** [review]
Leaving aside`equals` and `hash` subjects, LGTM

```
Results :

Tests run: 1953, Failures: 0, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:39 min
[INFO] Finished at: 2021-03-17T18:12:19-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by mwithi** [comment]
> what test is failing for you?
```
  initializationError(org.isf.priceslist.test.Tests): LTestPriceList;
```
I'll try again

**Comment by mwithi** [comment]
It was a temporary problem (" ... too many projects .... too much code ... too little time 😄")

LGTM
```
Results :

Tests run: 1953, Failures: 0, Errors: 0, Skipped: 5
```

**Pull request merged**
