### PR TITLE
[WIP] OP-387 MedicalType with testing  for OHServiceException and Null during MedicalTypeIoOperation.updateMedicalType

### PR DESCRIPTION
**Pull request by emecas**
TODO:

- [ ] Fix test failing only in IDE, but passing `mvn test`

### IDE Results:

image

### mvn Results

```
[26/Dec/2020 10:49:50] [:] INFO - Closing JPA EntityManagerFactory for persistence unit 'default'

Results :

Tests run: 489, Failures: 0, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:44 min
[INFO] Finished at: 2020-12-26T10:49:51-05:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by mwithi** [comment]
I'm setting to Draft since is still a WIP

**Comment by mwithi** [comment]
I'm setting to Draft since is still a WIP

**Comment by mwithi** [comment]
Hello @emecas is this PR still WIP? I think many things has changed so far that it could be closed and reopened if needed, wdyt?

**Comment by emecas** [comment]
> Hello @emecas is this PR still WIP? I think many things has changed so far that it could be closed and reopened if needed, wdyt?

I don't even remember what is this PR about :) I could take a look later and see if here is something we could save , for now I am with you , feel free to close this PR and I will reopens or add a new one if needed

**Comment by mwithi** [comment]
It was about the need (or not) to test known exception and so to have (or not) the exception stacktrace in the tests logs.
But anyway tests are maybe changed, so in case we can open a new one if needed.
Thanks!

**Pull request closed without merging**
