### PR TITLE
OP-974 transactional methods in manager not catching runtime exceptions

### PR DESCRIPTION
**Pull request by mwithi**
See OP-974.
Paired with https://github.com/informatici/openhospital-gui/pull/1319.

- [x] Change target type for `@TranslateOHServiceException`
- [x] Change pointcut for `org.isf.utils.db.OHServiceExceptionTranslator`
- [x] Add `@TranslateOHServiceException` to managers' methods with `@Transactional` annotation
- [x] Delete unused (old) `OHExceptionTranslator`
- [x] Remove useless annotations in services
- [x] Remove useless(?) `@Transactional` annotations in repositories
- [x] Add missing `@Modifying` annotations in repositories

Cc: @vir8wh47, @robertoc223388

### CODE REVIEW

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Review by emecas — APPROVED** [review]

**Review by robertoc223388 — APPROVED** [review]
Looks great!

**Comment by mwithi** [comment]
Thank you guys! please check also the latest commit

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Pull request merged**
