### PR TITLE
OP-101 WIP: upgrade to Spring 5

### PR DESCRIPTION
**Pull request by dbmalkovsky**
WIP of upgrading to Spring 5; [JIRA](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/OP-101)

Current tests: 52 fail, 348 pass of 400 tests.

### CODE REVIEW

**Comment by mwithi** [comment]
In Java CI with Maven:
Tests run: 398, Failures: 14, Errors: 19, Skipped: 0

Im my local (after merging with develop):
Tests run: 399, Failures: 31, Errors: 19, Skipped: 0

In IDE (Eclipse):
Tests run: 401, Failures: 33, Errors: 19, Skipped: 0

Most of the errors concern dates:
`org.isf.utils.exception.OHServiceException: org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [Wed Oct 07 00:00:00 CEST 2020] did not match expected type [java.util.Calendar (n/a)];`

A bunch of errors concern this:
`org.hibernate.LazyInitializationException: could not initialize proxy [org.isf.pricesothers.model.PricesOthers#1] - no Session`

**Comment by dbmalkovsky** [comment]
@mwithi   **Re: Errors concerning dates**

I have another alternative that appears to work; 

There is code of the form:
<pre>
		predicates.add(
			cb.between(opd,&lt;Date>get("visitDate"), dateFrom.getTime(), dateTo.getTime())
		);
</pre>

Changing it to:
<pre>
		Calendar calFrom = Calendar.getInstance();
		calFrom.setTime(dateFrom.getTime());
		Calendar calTo = Calendar.getInstance();
		calTo.setTime(dateTo.getTime());
		predicates.add(
			cb.between(opd.&lt;Calendar>get("visitDate"), calFrom, calTo)
		);
</pre>
and corrects the message:
 **Parameter value [Wed Oct 07 00:00:00 CEST 2020] did not match expected type [java.util.Calendar (n/a)];**

Not that it makes any difference to anyone but I find Hibernate and its friends more trouble than they are worth.  Not only are the generated queries overly complex but it makes debugging and query optimization difficult.  I once tool over a very large project that used Hibernate and it was performing poorly and hard to change.   We removed all the Hibernate code and used [MyBatis ](https://blog.mybatis.org/) instead and were able to make better and faster progress.  YMMV

**Comment by dbmalkovsky** [comment]
@mwithi **Re: Temporal**

Trying to use `@Temporal` on GregorianCalendar fields results in this message (even though GregorianCalendar is a subclass of Calendar):

                @Temporal should only be set on a java.util.Date or java.util.Calendar property

**Comment by dbmalkovsky** [comment]
Made some experimental changes to get around the "do not match expected type" messages.

Numbers are getting oh so slightly better.

Maven: Test run: 399, Failures: 20, Errors: 0, Skipped: 0
IDE (Intellij): Tests run: 401, Failures: 20, Passed: 381
Travis CI: Tests run: 399, Failures: 2, Errors: 0, Skipped: 0

The remaining two problems are in the Travis CI build are:

1. testIoGetAdmittedPatientsShouldNotFindWhenDischargeOutsideOfDateRange
2. testIoGetAdmittedPatientsShouldNotFindWhenAdmissionOutsideOfDateRange

In the local builds the other test failures are in code like `assertEquals(date, bill.getDate());` where `date` is a defined constant:

     private static GregorianCalendar date = new GregorianCalendar(10, 9, 8);

And `bill.getDate()` is returned from the database.   The values are consistently off by 3 minutes and 58 seconds.

I'm guessing this doesn't happen on the Travis CI build machines as they are running Linux and must have a more accurate storage implementation.

**Comment by mwithi** [comment]
> @mwithi **Re: Temporal**
> 
> Trying to use `@Temporal` on GregorianCalendar fields results in this message (even though GregorianCalendar is a subclass of Calendar):
> 
> ```
>             @Temporal should only be set on a java.util.Date or java.util.Calendar property
> ```

I've tried successfully this workaround:
```
@Column(name="LAB_EXAM_DATE")
@Temporal(TemporalType.DATE)
private Calendar examDate;		//it was GregorianCalendar 
...
public GregorianCalendar getExamDate() {
	return (GregorianCalendar) examDate;
}
```
This is necessary every time JavaTypes have been are wrongly mapped with unsuitable data type in the DB, but I would say that for the DDL sake, using @Temporal should be a best practise, wdyt?

Said so, when fields are mapped "correctly" (let's say GregorianCalendar with DATETIME or TIMESTAMP) still we have the problem of creating queries ignoring the time parte and we still use JPQ queries wrapping the fields with DATE(field) function in ordert to compare with Date. I don't know if JPA itself already offers a support for this usecase.

**Moreover**
I found something that is suggesting me to NOT using TIMESTAMP if not really needed ([here](https://stackoverflow.com/a/409305/5309541) and [here](https://stackoverflow.com/a/602038/5309541)):

> In MySQL 5 and above, TIMESTAMP values are converted from the current time zone to UTC for storage, and converted back from UTC to the current time zone for retrieval. (This occurs only for the TIMESTAMP data type, and not for other types such as DATETIME.)
>
> By default, the current time zone for each connection is the server's time. The time zone can be set on a per-connection basis, as described in MySQL Server Time Zone Support.

That might be the case when we store a GregorianCalendar mapped as TIMESTAMP and we get back something that is different from the stored object, but I will investigate further.

**Comment by tomek39856** [comment]
Regarding temporal problem jpa has something called attribute converter https://www.baeldung.com/jpa-attribute-converters
maybe this could help

**Comment by tomek39856** [comment]
There is also option to set timezone directly in hiberanate configuration. If you set it to UTC than everything will be converted to utc during save and converted back to local time on fetch

**Comment by dbmalkovsky** [comment]
@tomek39856 I'll try the converters approach tomorrow as I've been banging my head trying to define the datatype as `Calendar` but internally it stores it as `GregorianCalendar` which doesn't work.

And yes I also found `spring.jpa.properties.hibernate.jdbc.time_zone = UTC` but forgot to mention it.

So I'll need to clean things up and try again.    

And what fun, a new version of of the SpringFramework just got released; version 5.2.9

**Comment by dbmalkovsky** [comment]
I'm guessing converting to the JDK8 `java.time` package is off the table :smile:

**Comment by mwithi** [comment]
> Regarding temporal problem jpa has something called attribute converter https://www.baeldung.com/jpa-attribute-converters
> maybe this could help. Store in database as date and do conversion to GregorianCalendar when fetching/saving

The recommended and also less verbose way to store java.util.* seems to map them with `@Temporal` annotation; on the other hand, `@Converter` should be the best way back, when retrieving from the DB and storing in the JavaTypes (thus the casting above should be fine enough for GregorianCalendar, even if not beautiful). In other words, which one is better? Would also `@Temporal` help from the side hardy defining the DDL, especially now that things are a bit messed up between models and DB? After that, we can even refactor each field but caring about previous data already inserted in the DB (migration scripts).

TBH, I think in the end we should get rid of all `GregorianCalendar` and since we are using Java8 now, the suggested package for all date and time data types is `java.time.*`, that are natively supported (the main ones) by both JPA, Hibernate and JDBC. After that we should be quite safe about the stored and retrieved data and test should be not bothering us anymore.

But I want to see, looking at **openhospital-core** only, how is the situation now.

### Analysis
**in the DB:**
**TIMESTAMP** is used only two times: PAT_TIMESTAMP and SMS_DATE with a DEFAULT CURRENT_TIMESTAMP
**DATE** is used three times: LAB_EXAM_DATE, OPD_DATE_VIS, PAT_BDATE
**DATETIME** is used for all other fields hosting dates

**in the code:**
**java.util.GregorianCalendar** is used for **27 properties** of 12 entities:
<details>
<summary>27 properties 12 entries</summary>

```
org/isf/accounting/model/Bill.java:     					date;
org/isf/accounting/model/Bill.java:     					update;
org/isf/accounting/model/BillPayments.java:    			date;
org/isf/admission/model/Admission.java: 				admDate;      // admission date
org/isf/admission/model/Admission.java: 				opDate;       // operation date (null)
org/isf/admission/model/Admission.java: 				disDate;      // discharge date (null)
org/isf/admission/model/Admission.java: 				visitDate;    // ADM_PRG_DATE_VIS
org/isf/admission/model/Admission.java: 				deliveryDate; // ADM_PRG_DATE_DEL delivery date
org/isf/admission/model/Admission.java: 				ctrlDate1;    // ADM_PRG_DATE_CTRL1
org/isf/admission/model/Admission.java: 				ctrlDate2;    // ADM_PRG_DATE_CTRL2
org/isf/admission/model/Admission.java: 				abortDate;    // ADM_PRG_DATE_ABORT
org/isf/examination/model/PatientExamination.java:		pex_date;
org/isf/lab/model/Laboratory.java:      					registrationDate;
org/isf/malnutrition/model/Malnutrition.java:   			dateSupp;
org/isf/malnutrition/model/Malnutrition.java:   			dateConf;
org/isf/medicalstock/model/Lot.java:    					preparationDate;
org/isf/medicalstock/model/Lot.java:    					dueDate;
org/isf/medicalstock/model/Movement.java:       			date;
org/isf/medicalstockward/model/MovementWard.java:       date;
org/isf/opd/model/Opd.java:    						visitDate;
org/isf/opd/model/Opd.java:    						nextVisitDate;
org/isf/operation/model/OperationRow.java:    			opDate;
org/isf/patvac/model/PatientVaccine.java:       			vaccineDate;
org/isf/therapy/model/Therapy.java:     					GregorianCalendar[] dates;
org/isf/therapy/model/TherapyRow.java:  				startDate;
org/isf/therapy/model/TherapyRow.java:  				endDate;
org/isf/visits/model/Visit.java:        					date;
```

</details>

**java.util.Date** is used for **7 properties** of 4 entries:
<details>
<summary>7 properties of 4 entries</summary>

```
org/isf/dicom/model/FileDicom.java:     dicomStudyDate = null;
org/isf/dicom/model/FileDicom.java:     dicomSeriesDate = null;
org/isf/opd/model/Opd.java:     		date;
org/isf/patient/model/Patient.java:		birthDate;
org/isf/sms/model/Sms.java:     		smsDate;
org/isf/sms/model/Sms.java:     		smsDateSched;
org/isf/sms/model/Sms.java:     		smsDateSent;
```

</details>

**java.sql.Timestamp** is **never** used for mapping fields in models, but it is used 2 times for:
<details>
<summary>2 classes</summary>

```
org/isf/medicalstock/service/MedicalStockIoOperations.java:import java.sql.Timestamp;
org/isf/utils/excel/ExcelExporter.java:import java.sql.Timestamp;
```

</details>

**java.sql.Date** is **never** used for mapping fields in models, but it is 3 times for:
<details>
<summary>3 classes</summary>

```
org/isf/utils/excel/ExcelExporter.java:import java.sql.Date;
org/isf/utils/time/DateConverters.java:     * Converts the specified {@link java.sql.Date} to a {@link GregorianCalendar}.
org/isf/utils/time/RememberDates.java:  //java.sql.Date visitDate       = (opd.getVisitDate()==null?null:new java.sql.Date(opd.getVisitDate().getTimeInMillis()));
```

</details>

**java.sql.Time** is **never** used

We have also **org.joda.time** libraries, used in 1 model and some classes:
<details>
<summary>1 model and 3 classes</summary>

```
org/isf/opd/service/OpdIoOperations.java:import org.joda.time.DateTime;
org/isf/patient/model/Patient.java:import org.joda.time.DateTime;
org/isf/patient/model/Patient.java:import org.joda.time.Period;
org/isf/patient/model/Patient.java:import org.joda.time.PeriodType;
org/isf/patvac/service/PatVacIoOperations.java:import org.joda.time.DateTime;
org/isf/therapy/manager/TherapyManager.java:import org.joda.time.DateTime;
org/isf/utils/time/DateConverters.java:import org.joda.time.DateTime;
org/isf/utils/time/TimeTools.java:import org.joda.time.DateTime;
org/isf/utils/time/TimeTools.java:import org.joda.time.Period;
org/isf/utils/time/TimeTools.java:import org.joda.time.PeriodType;
org/isf/visits/manager/VisitManager.java:import org.joda.time.DateTime;```
```

</details>

### Confusion

In first sight, while in the DB things looks quite fine (except for some fields names and their residual usefulness since now we have audit fields - OP-80), I think there is a bit of confusion in the models structure in the code; we should opt for a standard way. But before that, and so changing JavaTypes right away, maybe it could advisable to fix how JPA and Hibernate should persist those fields as they are mapped in the DB now (in case I can do a deep analysis).

After that, as stated above, we could refactoring whatever we like.

What do you think guys?

**Comment by mwithi** [comment]
> I'm guessing converting to the JDK8 `java.time` package is off the table 😄

Not at all, just mentioned that above 😁

**Comment by mwithi** [comment]
About `spring.jpa.properties.hibernate.jdbc.time_zone = UTC` it is the way to go, but it seems is highly not recommended to use Hibernate for mapping zone time because it passes by the JVM local time before to land on the DB, if I understood properly. Anyway, a part this, I'm guessing if we really need to use Timestamp for those few fields...

**Comment by mwithi** [comment]
> And what fun, a new version of of the SpringFramework just got released; version 5.2.9

Indeed, dependabot is promptly for it https://github.com/informatici/openhospital-gui/pull/212 😀
We can update this PRs and close the new #212, ok?

**Comment by dbmalkovsky** [comment]
After recreating my environment after my other failed attempts this attempt uses the `AttributeConverter` approach (see the file `org.isf.utils.db.DateCalendarConverter`) and it blindly applies it to all fields.

Results:
Maven: Tests run: 430, Failures: 1, Errors: 0, Skipped: 0
IDE (Intellij): Tests run: 432, Failures: 1, Passed: 431
Travis CI: Tests run: 430, Failures: 2, Errors: 0, Skipped: 0

Next step is to see about the remaining failure(s).

**Comment by dbmalkovsky** [comment]
Current Results after last commit:

Maven: Tests run: 430, Failures: 0, Errors: 0, Skipped: 0
IDE (Intellij): Tests run: 432, Failures: 0, Passed: 432
Travis CI: Tests run: 430, Failures: 0, Errors: 0, Skipped: 0

Next is fixing `AuditorAwareImpl`.

**Comment by dbmalkovsky** [comment]
@uni2grow @mwithi @tomek39856 I could use a review of the changes I made to `AuditorAwareImpl`.  If OK and everyone is happy with the persistence changes then we might have a first pass of moving to Spring 5 :smile:

Thank you for everyone's help and patience. 👍

**Comment by mwithi** [comment]
> @uni2grow @mwithi @tomek39856 I could use a review of the changes I made to `AuditorAwareImpl`. If OK and everyone is happy with the persistence changes then we might have a first pass of moving to Spring 5 😄
> 
> Thank you for everyone's help and patience. 👍

great work indeed! just give us a little time to have a second pass... 🙌 
meanwhile you could check that other related PR on gui? https://github.com/informatici/openhospital-gui/pull/212

**Comment by dbmalkovsky** [comment]
@mwithi I looked at [informatici/openhospital-gui#212](https://github.com/informatici/openhospital-gui/pull/212) and there are total of 6 references to springframework and they all appear to be related to getting the application context and looking up a bean reference.   It looks safe to me.

**Comment by mwithi** [comment]
> @mwithi I looked at [informatici/openhospital-gui#212](https://github.com/informatici/openhospital-gui/pull/212) and there are total of 6 references to springframework and they all appear to be related to getting the application context and looking up a bean reference. It looks safe to me.

you mean it's safe to merge straight away?
anyway I will give them a twisht, core+gui both bumped

**Comment by dbmalkovsky** [comment]
Yes I think it safe to merge; if it breaks it will break fast :smile:

**Comment by pviotti** [comment]
I haven't followed this conversation, but FYI and not to go in two different directions regarding time data type:
in [this PR](https://github.com/informatici/openhospital-core/pull/120) to upgrade mysql java connector, I changed all GregorialCalendar and `java.util.Date` to `java.sql.Date` and it solved all test failures I had regarding dates, timezone etc (see [this comment ](https://github.com/informatici/openhospital-core/pull/120#issuecomment-693684161) for more info). This may solve some of your time data problem too (or not).

**Comment by dbmalkovsky** [comment]
Update spring-boot to 2.3.4.RELEASE
Add `spring.boot.version` property to pom.xml, set it to `2.3.4.RELEASE` and then used the property
Also commented out duplicate dependency definition (see lines 258-276); should most likely just be duplicated.

With these changes everything continues to pass with maven, IDE, and Travis CI.

**Comment by dbmalkovsky** [comment]
With regards to [Upgrade mysql-connector-java to its last version](https://github.com/informatici/openhospital-core/pull/120)) I decided to see if I could replace H2 with MySQL and see what happened.

- So I installed MySQL my linux box
- Created user `isf` with password `isf123`:             `create user 'isf'@'localhost' identified by 'isf123';`
- Granted privileges to isf:                                      `grant all  on *.* to 'isf'@'localhost';`
- Made sure there wasn't a db:                               `drop database if exists oh;`
- Created the db:                                                     `create database oh character set utf8;`
- Added the new updated connector jar to `pom.xml`:                `<version>8.0.21</version>`
- Recompiled the project
- Fixed the compiler error as was done in PR 120; that is remove the `CommunicationsException` import and change the code from `CommunicationsException` to `Exception`
- Recompile the project and now it is clean
- Update the `test/resources/database.properties` to look like:
 <pre>
    jdbc.class=com.mysql.cj.jdbc.Driver
    jdbc.url=jdbc:mysql://localhost:3306/oh
    hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    hibernate.hbm2ddl.auto=update
 
    jdbc.username=isf
    jdbc.password=isf123
 </pre> 
- Then ran all the 432 tests and found about 20+ errors.
- The errors fell into two categories:    dates not matching up correctly and the default handling of `GROUP BY`
- For dates that was fixed by adding `serverTimezone` to the `url`:  
 
 <pre>
  jdbc.url=jdbc:mysql://localhost:3306/oh?serverTimezone=US/Easter</pre>
 
- For `GROUP BY` (see discussion [here](https://dev.mysql.com/doc/refman/8.0/en/group-by-handling.html)) issued the following command in mysql to change the default:
 
 <pre>
    SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')); </pre>

- Dropped and recreated the `oh` database
- Reran the 432 tests on the empty database and all 432 test passed.  :smile:

**Comment by pviotti** [comment]
Those are indeed two viable *workarounds* (i.e. using timezones and disabling a sensible flag on server side), but I'd prefer to go for a proper fix: using better ORM mapping for time-related data and changing non-deterministic `group by` queries :)
Thanks for the test though, good to have a confirmation that things can work, in some other way (btw a quicker way to spin up the db would be using `docker-compose up` with the Docker files in the root folder).

**Comment by mwithi** [comment]
I had not time to have a second pass on this huge work, hope in the weekend. Anyway I agree with @pviotti that is it is better to find final solutions (workadounds may not apply in all cases) but I'm wondering if somebody is taking in consideration the suggestion of using @Temporal annotation as a middle-step toward a standardization, I see at it like the needed "contract" between ORM and JavaType used at the moment. Wdyt?

**Comment by dbmalkovsky** [comment]
Getting proper mapping all around is the best long term solution.   FWIW, my experience with `@Temporal` wasn't all that great; I spend a far amount of time trying to get the current data type definitions to work.   But that might be a factor of the fact that I didn't spend the time to analyze what the ***proper*** data types should be before using `@Temporal`.

**Comment by mwithi** [comment]
Maybe the easiest way is to just adopt `java.time.*` all over the code for the entities and assure that, apart tests, the rest of the application (`gui` and `api`) is still working properly, especially when comparing dates that now are passed as `GregorianCalendar`. 

About this I'm still having a glitch with this:
> Said so, when fields are mapped "correctly" (let's say GregorianCalendar with DATETIME or TIMESTAMP) still we have the problem of creating queries ignoring the time part and we still use JPQL queries wrapping the fields with DATE(field) function in order to compare them with a Date. I don't know if JPA itself already offers a support for this usecase.

**Comment by mwithi** [comment]
Superseded by #120 .

@dbmalkovsky @emecas please reach us on [Slack](https://join.slack.com/t/openhospitalworkspace/shared_invite/zt-cg9iu1d0-sjTuWWziFgcDqiTWyMJBAw)!

**Pull request closed without merging**
