### PR TITLE
Use a proper maven project layout

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by mwithi** [comment]
After moving all files following the Maven Standard Layout, 32/347 tests fails, mostly related to equal assertions between dates.

Is there any libraries scope change that I don't see?

I opened https://github.com/larsgrefer/openhospital-core/pull/1
@emecas @larsgrefer @pviotti

**Comment by mwithi** [comment]
UPDATE: my fork Travis build is passing:
https://travis-ci.com/github/mwithi/openhospital-core/builds/168925857

**Comment by pviotti** [comment]
I don't quite understand why you opened https://github.com/larsgrefer/openhospital-core/pull/1 , and I'm a bit confused by the branching model: `1.10-pre` is going to be merged into `1.10` and `1.10` into master and then tagged, right? (and we get rid of this custom and confusing branching model after this release right? :stuck_out_tongue: )

If it was up to me, I'd probably redo the changes on this PR from scratch - there have been lots of commits since it was opened: trying to merge them might be lot of effort, and we might risk losing changes.

**Comment by emecas** [comment]
@mwithi @larsgrefer @pviotti added all comments about what I have experimented until now regarding to this change here: https://github.com/larsgrefer/openhospital-core/pull/1#issuecomment-636483375  

I am wondering if you get similar results ?

**Comment by mwithi** [comment]
It's ok @pviotti, created:
- https://github.com/informatici/openhospital-core/pull/101
- https://github.com/informatici/openhospital-gui/pull/156

problems on test are the same

**Pull request closed without merging**
