### PR TITLE
[OP-229] patient profile photo optional and patient search fix

### PR DESCRIPTION
**Pull request by tomek39856**

### CODE REVIEW

**Review by mwithi — COMMENTED** [review]
Not sure how the changes should resolve the issue in the title, but anyway what I found is on a fresh DB (created with create_all_en.sql):
```
mysql>  select * from patient;
+--------+------------+-----------+---------------------+----
| PAT_ID | PAT_FNAME  | PAT_SNAME | PAT_NAME            | PAT
+--------+------------+-----------+---------------------+----
|      0 | Patient    | Null      | Null Patient        | NUL
+--------+------------+-----------+---------------------+----
1 rows in set (0.00 sec)

mysql>  select * from patient_profile_photo;
+----------------------+-----------+
| PAT_PROFILE_PHOTO_ID | PAT_PHOTO |
+----------------------+-----------+
|                    1 | NULL      |
+----------------------+-----------+
```

After first insert:
```
+--------+------------+-----------+---------------------+----
| PAT_ID | PAT_FNAME  | PAT_SNAME | PAT_NAME            | PAT
+--------+------------+-----------+---------------------+----
|      0 | Patient    | Null      | Null Patient        | NUL
|      1 | Alessandro | Domanico  | Alessandro Domanico | 198
+--------+------------+-----------+---------------------+----

+----------------------+-----------+
| PAT_PROFILE_PHOTO_ID | PAT_PHOTO |
+----------------------+-----------+
|                    1 | NULL      |
+----------------------+-----------+
|                    2 | NULL      |
+----------------------+-----------+
```

After attaching photo:
```
+----------------------+-----------+
| PAT_PROFILE_PHOTO_ID | PAT_PHOTO |
+----------------------+-----------+
|                    1 | NULL      |
+----------------------+-----------+
|                    2 | BLOB      |
+----------------------+-----------+
```

**Comment by tomek39856** [comment]
Sorry name was wrong, regarding patient photo there is one change relation is now optional but it should go together with gui fix from other PR, rest of the pr solves patient search problem look at OP-229 comments

**Review by mwithi — APPROVED** [review]
Everything works as expected now, with https://github.com/informatici/openhospital-gui/pull/202

Thanks!!

**Comment by mwithi** [comment]
> look at [OP-229](https://openhospital.atlassian.net/browse/OP-229) comments

Sorry, I forgot to refresh the page already opened since last Friday 😅

**Pull request merged**
