### PR TITLE
OP-727 prefix table names

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-727

All the CORE junit tests pass locally.

This is just the start of the changes; I know that all the report generation files need to be updated but I'm not familiar with the tool.

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
@mizzioisf @mwithi is this on the right path?   Other than the report generation that is?

**Comment by pviotti** [comment]
Reminder: 
- [ ] remove `NON_KEYWORDS=USER` from `src/test/resources/database.properties`, which was set as workaround in #600 .

**Comment by dbmalkovsky** [comment]
See https://github.com/informatici/openhospital-gui/pull/1294 for the corresponding report changes

**Comment by dbmalkovsky** [comment]
During interactive testing I found that there was an issue with foreign keys; the latest commit fixes that issue.

**Comment by mwithi** [comment]
Usual problem between command line and Eclipse (Run as JUnit)...

not yet understood but maybe can give some hints:

```
core> mvn clean install 
...
Tests in error:
  org.isf.dicom.test.TestFileSystemDicomManager: Text 'Sat Aug 01 10:02:03 2020' could not be parsed at index 0
  org.isf.dicom.test.Tests: Text 'Sat Aug 01 10:02:03 2020' could not be parsed at index 0
  org.isf.dicom.test.TestSqlDicomManager: Text 'Sat Aug 01 10:02:03 2020' could not be parsed at index 0
  testMgrGetLaboratoryForPrintMultipeResultsRows[Test with LABEXTENDED=false](org.isf.lab.test.Tests): Index 0 out of bounds for length 0
  testMgrGetLaboratoryForPrintMultipeResultsRows[Test with LABEXTENDED=true](org.isf.lab.test.Tests): Index 0 out of bounds for length 0

Tests run: 1857, Failures: 31, Errors: 5, Skipped: 4
```

in Eclipse (same parse error for all 3 failing tests):
image

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

I will stage it for a while for more testing...

**Comment by mwithi** [comment]
> in Eclipse (same parse error for all 3 failing tests):

new issue has been open for DICOM tests, see OP-967.

**Pull request merged**
