### PR TITLE
OP-404 increase coverage in visits; format Manager file

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Coverage before:
image

Coverage after:
image

NOTE:

- There is one line of code I can't reach in `VisitManager`
- See [OP-403](https://openhospital.atlassian.net/browse/OP-403) for two PRs related to other changes in needed in VisitManager

### CODE REVIEW

**Review by mwithi — APPROVED** [review]
LGTM, thanks!
```
Results :

Tests run: 951, Failures: 0, Errors: 0, Skipped: 1
```

**Review by emecas — COMMENTED** [review]
LGTM, just I am not fan of testing dates and times using hard coded values 

thanks @dbmalkovsky 
```

Results :

Tests run: 775, Failures: 0, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2021-01-19T20:39:53-05:00
[INFO] ------------------------------------------------------------------------

```

**Comment by emecas** [comment]
> 
> 
> LGTM, thanks!
> 
> ```
> Results :
> 
> Tests run: 951, Failures: 0, Errors: 0, Skipped: 1
> ```

why 951 tests? do you have uncommitted local code?

**Comment by mwithi** [comment]
> why 951 tests? do you have uncommitted local code?

I have merged many PRs in the last days... could you confirm your number?

**Comment by dbmalkovsky** [comment]
If one checks out only this PR without rebasing on the latest develop branch you get the 700 number.   If you checkout the latest develop branch you'll find 941 tests.   Thus I'm guessing the 951 comes running against a recent branch on top of develop.

**Comment by mwithi** [comment]
> If one checks out only this PR without rebasing on the latest develop branch you get the 700 number. If you checkout the latest develop branch you'll find 941 tests. Thus I'm guessing the 951 comes running against a recent branch on top of develop.

I always test the PR on top of the latest develop, like in _command line instructions_ at the bottom of the page, so they should be a bit more than the ones develop.

Before https://github.com/informatici/openhospital-core/pull/291/commits/aaa079fd40bea82c3fb593052c1413c9a4928e40 I was having: `Results : Tests run: 963, Failures: 0, Errors: 0, Skipped: 1` but now is giving checks failures.

**Comment by dbmalkovsky** [comment]
Replaced with this [PR 299](https://github.com/informatici/openhospital-core/pull/299).  Closing this PR.

**Pull request closed without merging**
