### PR TITLE
OP-392 increase coverage, format managers, and fix a few NPEs

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Coverage before:
image

Coverage after:
image

Every single line and method has not been covered because some of them were impossible to access.
I have already spent too many days getting the coverage that is here and fixing some of the code (typically NPEs or catching an exception and then immediately throwing it again when the method defines that exception as being part of the contract, etc.)

I did reformat the manager files and removed unused logger definitions.

This isn't perfect but it is better than when I started.

### CODE REVIEW

**Review by emecas — COMMENTED** [review]
These 3 tests are failing when I run them locally

1c194ac439

image
```

[06/Jan/2021 22:56:49] [:] INFO - Closing JPA EntityManagerFactory for persistence unit 'default'

Results :

Tests in error:
  testMgrPrepareChargingMovement(org.isf.medicalstock.test.Tests)
  testMgrPrepareDischargingMovementIsAutomaticLotOut(org.isf.medicalstock.test.Tests)
  testMgrPrepareDischargingMovement(org.isf.medicalstock.test.Tests)

Tests run: 772, Failures: 0, Errors: 3, Skipped: 2

```
@dbmalkovsky any idea?

**Comment by dbmalkovsky** [comment]
@emecas The problem is that the code generates a date for the Movement object that works only if the current date is after Feb 2 👎   So when I tested this in December all was well.

````
	private GregorianCalendar now = new GregorianCalendar();
	private GregorianCalendar date = new GregorianCalendar(now.get(Calendar.YEAR), 2, 2);
````
I'll fix the code.

**Comment by dbmalkovsky** [comment]
@emecas `mvn clean test`:
````
Results :

Tests run: 772, Failures: 0, Errors: 0, Skipped: 2
````

**Comment by emecas** [comment]
Thank David, I'd like to get a better understanding about your solution.

## Case 1

For example, for the case: `testMgrPrepareChargingMovement() ` before the last commit, the  error was located in this assertion 
`assertThat(movStockInsertingManager.newMultipleChargingMovements(movements, "refNo")).isTrue();` because a OHDataValidationException during `MovStockInsertingManager.validateMovement` during the evaluetion of this condition:

```
if (movDate.after(today)) {
	errors.add(new OHExceptionMessage("movementDateInFutureError",
			MessageBundle.getMessage("angal.medicalstock.multiplecharging.futuredatenotallowed"), //$NON-NLS-1$
			OHSeverityLevel.ERROR));
}
```

### where:

##### movDate :

```
java.util.GregorianCalendar[
   time=1614661200000,
   areFieldsSet=true,
   areAllFieldsSet=true,
   lenient=true,
   zone=sun.util.calendar.ZoneInfo[
     id="America/New_York",offset=-18000000,dstSavings=3600000,useDaylight=true,transitions=235,
	 lastRule=java.util.SimpleTimeZone [
		  id=America/New_York,offset=-18000000,dstSavings=3600000 ,
		  useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek= 1,
		  startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1, 
		  endTime=7200000,endTimeMode=0
 	 ] 
   ],
   firstDayOfWeek=1,
   minimalDaysInFirstWeek=1,
   ERA=1,
   YEAR=2021,
   MONTH=2,
   WEEK_OF_YEAR=10,
   WEEK_OF_MONTH=1,
   DAY_OF_MONTH=2,
   DAY_OF_YEAR=61,
   DAY_OF_WEEK=3,
   DAY_OF_WEEK_IN_MONTH=1,
   AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,
   ZONE_OFFSET=-18000000,
   DST_OFFSET=0]

```

### and

#### today:

``` 
java.util.GregorianCalendar[
   time=1610026498538,
   areFieldsSet=true,
   areAllFieldsSet=true,
   lenient=true,
   zone=sun.util.calendar.ZoneInfo[
	 id="America/New_York",offset=-18000000,dstSavings=3600000,useDaylight=true,transitions=235,
	 lastRule=java.util.SimpleTimeZone[
		  id=America/New_York,offset=-18000000,dstSavings=3600000,
		  useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,
		  startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,
		  endTime=7200000,endTimeMode=0
	 ]
   ],
   firstDayOfWeek=1,
   minimalDaysInFirstWeek=1,
   ERA=1,
   YEAR=2021,
   MONTH=0,
   WEEK_OF_YEAR=2,
   WEEK_OF_MONTH=2,
   DAY_OF_MONTH=7,
   DAY_OF_YEAR=7,
   DAY_OF_WEEK=5,
   DAY_OF_WEEK_IN_MONTH=1,
   AM_PM=0,HOUR=8,HOUR_OF_DAY=8,MINUTE=34,SECOND=58,MILLISECOND=538,
   ZONE_OFFSET=-18000000,
   DST_OFFSET=0]
```

I got to pass it by doing these 2 changes in `TestMovement`:
```

diff --git a/src/test/java/org/isf/medicalstock/test/TestMovement.java b/src/test/java/org/isf/medicalstock/test/TestMovement.java
index de3eaaa7..3be9dbce 100644
--- a/src/test/java/org/isf/medicalstock/test/TestMovement.java
+++ b/src/test/java/org/isf/medicalstock/test/TestMovement.java
@@ -36,7 +36,12 @@ import org.isf.ward.model.Ward;

 public class TestMovement {

-       private GregorianCalendar date = new GregorianCalendar(2000, 2, 2);
+//<<<<<<< Updated upstream
+//     private GregorianCalendar date = new GregorianCalendar(2000, 2, 2);
+//=======
+       private GregorianCalendar now = new GregorianCalendar();
+       private GregorianCalendar date = now; //now.set(GregorianCalendar.YEAR, now.get(GregorianCalendar.YEAR)-1); //new GregorianCalendar(now.get(Calendar.YEAR), 2, 2);
+//>>>>>>> Stashed changes
        private int quantity = 10;
        private String refNo = "TestRef";

@@ -54,6 +59,7 @@ public class TestMovement {
                        _setParameters(movement, medical, movementType, ward, lot, supplier);
                } else {
                        // Create Movement with all parameters
+                       date.set(now.get(Calendar.YEAR)-1, now.get(Calendar.MONTH), now.get(Calendar.DATE));
                        movement = new Movement(medical, movementType, ward, lot, date, quantity, supplier, refNo);
                }



```

## Case 2

Then there is a second category of tests failing, because a problem in the ranges of dates defined under `TestLot` (`preparationDate `and  `dueDate`) and the specific values in each tests for  `fromDate `and `toDate`, I will cover those later in a different comment.

image

**Comment by dbmalkovsky** [comment]
It really doesn't matter what "year" is used as long as things are consistent.  So instead of making multiple changes to make sure the dates are consistent relative to "now" I just hard coded them to a specific year.   I found it much more straightforward (and I had hoped easier to understand) than tracking down all the places that would need adjust (as you seem to be doing).   Just a difference in implementation.

**Comment by emecas** [comment]
> 
> 
> It really doesn't matter what "year" is used as long as things are consistent. So instead of making multiple changes to make sure the dates are consistent relative to "now" I just hard coded them to a specific year. I found it much more straightforward (and I had hoped easier to understand) than tracking down all the places that would need adjust (as you seem to be doing). Just a difference in implementation.

Since this issue is focus on coverage, your implementation does what it supposes to do. 

I was trying to get a better understanding  in order to generalize and simplify,  avoiding to have to do multiple changes or hard code the initialization for each tests.  As well as evaluating if making it works relative to the run time (keeping the time dynamic) and/or adding some random variations on the tested times and ranges while the tests run, could uncover issues.

**Review by emecas — APPROVED** [review]

**Comment by emecas** [comment]
> 
> 
> It really doesn't matter what "year" is used as long as things are consistent. So instead of making multiple changes to make sure the dates are consistent relative to "now" I just hard coded them to a specific year. I found it much more straightforward (and I had hoped easier to understand) than tracking down all the places that would need adjust (as you seem to be doing). Just a difference in implementation.

Since this issue is focus on coverage, your implementation does what it supposes to do. 

I was trying to get a better understanding  in order to generalize and simplify,  avoiding to have to do multiple changes or hard code the initialization for each tests.  As well as evaluating if making it works relative to the run time (keeping the time dynamic) and/or adding some random variations on the tested times and ranges while the tests run, could uncover issues.

**Review by mwithi — APPROVED** [review]
Thanks guys!
```
Results :

Tests run: 927, Failures: 0, Errors: 0, Skipped: 1
```

**Pull request merged**
