### PR TITLE
Removing local (Maven) repo as continuation of #325

### PR DESCRIPTION
**Pull request by mwithi**
As continuation of #325 we can remove the local Maven repo and its reference in pom.xml

### CODE REVIEW

**Comment by mizzioisf** [comment]
I can confirm it's working, nice !

**Review by emecas — COMMENTED** [review]
Any particular approach for testing this is required,  i asking since as soon as I tried to run the tests I got a dependency error like this:

```
/openhospital/core (mwithi_delete_local_maven_repo)
$ mvn clean test
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< org.isf:OH-core >---------------------------
[INFO] Building OpenHospital-core 1.10
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from dcm4che: https://www.dcm4che.org/maven2/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
Downloading from JFrog: https://packages.atlassian.com/maven-3rdparty-legacy-local/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.729 s
[INFO] Finished at: 2021-03-09T07:59:35-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project OH-core: Could not resolve dependencies for project org.isf:OH-core:jar:1.10: Failed to collect dependencies at net.sf.jasperreports:jasperreports:jar:6.14.0 -> com.lowagie:itext:jar:2.1.7.js8: Failed to read artifact descriptor for com.lowagie:itext:jar:2.1.7.js8: Could not transfer artifact com.lowagie:itext:pom:2.1.7.js8 from/to dcm4che (https://www.dcm4che.org/maven2/): Connect to www.dcm4che.org:443 [www.dcm4che.org/195.201.27.249] failed: Connection timed out: connect -> [Help 1]
```

**Comment by mwithi** [comment]
Hi @emecas , could you try to delete any previous com.lowagie.itext folder downloaded in your local maven cache?

**Comment by emecas** [comment]
> 
> 
> Hi @emecas , could you please try to delete any previous `com/lowagie/itext` folder downloaded in your local maven cache?
> 
> Anyway it seems a temporary problem on connecting to [www.dcm4che.org:443](http://www.dcm4che.org:443), not related to the changes in this PR

That is what I thought , I removed from my local a couple times, it attempted download it from 6 different places and finally said `Downloaded from central:` , but it failed as well. I will try again later.


```
openhospital/core (mwithi_delete_local_maven_repo)
$ mvn clean test
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< org.isf:OH-core >---------------------------
[INFO] Building OpenHospital-core 1.10
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from dcm4che: https://www.dcm4che.org/maven2/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
Downloading from JFrog: https://packages.atlassian.com/maven-3rdparty-legacy-local/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/lowagie/itext/2.1.7.js8/itext-2.1.7.js8.pom
Downloading from dcm4che: https://www.dcm4che.org/maven2/com/lowagie/itext/2.1.7/itext-2.1.7.pom
Downloading from JFrog: https://packages.atlassian.com/maven-3rdparty-legacy-local/com/lowagie/itext/2.1.7/itext-2.1.7.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/lowagie/itext/2.1.7/itext-2.1.7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/lowagie/itext/2.1.7/itext-2.1.7.pom (3.0 kB at 23 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.769 s
[INFO] Finished at: 2021-03-09T08:22:54-06:00
[INFO] ------------------------------------------------------------------------
```

**Comment by mwithi** [comment]
I've excluded the `com.lowagie.itext-2.1.7.js8` that seems not existing, and maven search it in the first non-maven central repo defined in the pom.xml, the dcm4che, of course not finding it. JasperReport 6.14.0 should work fine even with `com.lowagie.itext-2.1.7`

Nevertheless this raised the issue on dcm4che repository... time to change it? See OP-347...

**Review by emecas — COMMENTED** [review]
LGTM

```
Results :

Tests run: 1953, Failures: 0, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:19 min
[INFO] Finished at: 2021-03-09T13:01:07-06:00
[INFO] ------------------------------------------------------------------------
```

**Comment by mwithi** [comment]
A local Maven repo since still very useful to address problems like #359 so I close this PR.

**Pull request closed without merging**
