### PR TITLE
OP-388: Class rename of MedicaldsrstockmovTypeBrowserManager

### PR DESCRIPTION
**Pull request by Verdoso**
Class rename following conventions as stated in https://openhospital.atlassian.net/browse/OP-388

This PR should be approved in sync with the PRs that adapt this change in openhospital-ui and openhospital-gui as both use the class.

### CODE REVIEW

**Comment by Verdoso** [comment]
Related PRs are:
- openhospital-gui: https://github.com/informatici/openhospital-gui/pull/1761
- openhospital-api: https://github.com/informatici/openhospital-api/pull/266

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Comment by mwithi** [comment]
All over the application the original name (coming from Medical class) is:

```
/**
 * ------------------------------------------
 * MedicalDSR - model for the Medical DSR (Drugs Surgery Rest): represents a medical
 * -----------------------------------------
 */
```

This reflects to DB tables too.

Do you think we can keep the same terminology in classes? otherwise MedicaldsrstockmovTypeBrowserManager is not the only one that need to be changed.

**Comment by dbmalkovsky** [comment]
Good catch; I forgot about the db and reports.

**Review by dbmalkovsky — COMMENTED** [review]
Looks like I shouldn't have approved this :(

**Comment by mwithi** [comment]
> Looks like I shouldn't have approved this :(

No worries, we both look after for this reason too :)
If you want you can dismiss the reivew

image

**Comment by Verdoso** [comment]
Updated all classes that I found related to MedicalDsrStockMovementType* to be consistent

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
