### PR TITLE
OP-412 increase coverage in therapy; format Manager file; fix NPE

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Coverage before:
image

Coverage after:
image

While writing a test for `public ArrayList<Medical> getMedicalsOutOfStock(ArrayList<Therapy> therapies) ` in `org.isf.therapy.manager.TherapyManager` there was a NPE generated.  The reason was that the method started off with
````
	public ArrayList<Medical> getMedicalsOutOfStock(ArrayList<Therapy> therapies) throws OHServiceException {
		MovWardBrowserManager wardManager = new MovWardBrowserManager();
		MedicalBrowsingManager medManager = new MedicalBrowsingManager();
````

Both `wardManager` and `medManager` should be `@Autowired` instead of constructing new instances as they were written the calls made in the managers to the `service` level  generated NPE.   To fix the NPEs both lines were removed and the `managers` were instead `@Autowired`.

### CODE REVIEW

**Review by emecas — CHANGES_REQUESTED** [review]
@dbmalkovsky

May you fix conflicting file:

    src/main/java/org/isf/therapy/service/TherapyIoOperations.java

 @mwithi I was starting the review you requested, but I noticed

**Comment by dbmalkovsky** [comment]
@emecas Conflict in the javadoc resolved.

**Review by dbmalkovsky — COMMENTED** [review]
Conflict resolved

**Review by emecas — APPROVED** [review]
@dbmalkovsky 

LGTM, Regarding to coverage and manager's format 

thanks

```
Results :

Tests run: 1105, Failures: 0, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2021-01-25T11:53:44-05:00
[INFO] ------------------------------------------------------------------------
```



CC. @mwithi 

There are 4 exception traces during the build, but since you have mentioned the why(s), or at least part of them have been identified before, all them could be revisited in (a) different issue(s).

1)  Code:
```
	public Vaccine findVaccine(String code)
	{
		if (code != null) {
			return repository.findOne(code);
		}else
			throw new IllegalArgumentException("code must not be null");
	} 
```

Test and Trace
```
       @Test
	public void testIoFindVaccineNull() throws Exception {
		assertThatThrownBy(() -> vaccineIoOperation.findVaccine(null))
				.isInstanceOf(RuntimeException.class);
	}

	java.lang.IllegalArgumentException: code must not be null
	at org.isf.vaccine.service.VaccineIoOperations.findVaccine(VaccineIoOperations.java:123)
	at org.isf.vaccine.service.VaccineIoOperations$$FastClassBySpringCGLIB$$eb2414f9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
```



2) Code:
```
	public VaccineType findVaccineType(String code)
	{
		if (code != null) {
			return repository.findOne(code);
		}else
			throw new IllegalArgumentException("code must not be null");
	} 
```

Test and Trace
```
	@Test
	public void testMgrFindVaccineTypeNull() throws Exception {
		assertThatThrownBy(() -> vaccineTypeBrowserManager.findVaccineType(null))
				.isInstanceOf(RuntimeException.class);
	}

	java.lang.IllegalArgumentException: code must not be null
	at org.isf.vactype.service.VacTypeIoOperation.findVaccineType(VacTypeIoOperation.java:116)
	at org.isf.vactype.service.VacTypeIoOperation$$FastClassBySpringCGLIB$$b94b7f20.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
```
	
	
3) Code:
```
  	@EventListener
	public void handle(PatientMergedEvent patientMergedEvent) {
		this.patientMergedEvent = patientMergedEvent;
		if (shouldFail) {
			throw new RuntimeException("failure testing");
		}
	}
```
	
Test and Trace
```
	@Test
	public void testIoFindWardNull() throws Exception {
		assertThatThrownBy(() -> wardIoOperation.findWard(null))
				.isInstanceOf(OHServiceException.class);
	}

	No EXIF information found for image: image.0007.jpg

        java.lang.RuntimeException: failure testing
	at org.isf.patient.TestPatientMergedEventListener.handle(TestPatientMergedEventListener.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```


4) Code:
```
	public Ward findWard(String code) throws OHServiceException
	{
		if (code != null) {
			return repository.findOne(code);
		}else
			throw new IllegalArgumentException("code must not be null");
	}
```

Test and Trace
```
	@Test
	public void testIoFindWardNull() throws Exception {
		assertThatThrownBy(() -> wardIoOperation.findWard(null))
				.isInstanceOf(OHServiceException.class);
	}

	java.lang.IllegalArgumentException: code must not be null
	at org.isf.ward.service.WardIoOperations.findWard(WardIoOperations.java:165)
	at org.isf.ward.service.WardIoOperations$$FastClassBySpringCGLIB$$cbff813d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
```

**Comment by mwithi** [comment]
> There are 4 exception traces during the build, but since you have mentioned the why(s), or at least part of them have been identified before, all them could be revisited in (a) different issue(s).

Ok let's create an issue for that!
```
Results :

Tests run: 1105, Failures: 0, Errors: 0, Skipped: 1
```

**Review by mwithi — APPROVED** [review]

**Comment by emecas** [comment]
> 
> 
> > There are 4 exception traces during the build, but since you have mentioned the why(s), or at least part of them have been identified before, all them could be revisited in (a) different issue(s).
> 
> Ok let's create an issue for that!
> 
> ```

Created OP-416

**Pull request merged**
