### PR TITLE
OP-895 implement password strength test

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-895

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
This is the list of special characters that are tested for: `@#$%^&+=`

**Comment by mwithi** [comment]
> This is the list of special characters that are tested for: `@#$%^&+=`

I would add also question and exclamation marks (!?) and maybe dash and underscore (-_).

**Comment by dbmalkovsky** [comment]
The list is now `@#$%^&+=!-_?`

**Comment by mwithi** [comment]
> The list is now `@#$%^&+=!-_?`

Thanks @dbmalkovsky, more reasoning under the issue itself.

**Comment by dbmalkovsky** [comment]
The list of special characters is now `_$&+,:;=\?@#|/'<>.^*()%!-`.  I also added a unit test

**Review by mwithi — APPROVED** [review]
LGTM and overtested 😆. Thanks a lot!

**Pull request merged**
