### PR TITLE
OP-405 increase coverage in ward; format Manager file

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Coverage before:
image

Coverage after:
image

NOTE:  I had to fix the default email address used in setup() to be valid

### CODE REVIEW

**Review by mwithi — COMMENTED** [review]
It says ok, but with one exception:
```
Results :

Tests run: 961, Failures: 0, Errors: 0, Skipped: 1
```
<details>
<summary>Exception</summary>
Running org.isf.ward.test.Tests
[13/ene./2021 23:42:14] [:] INFO - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener]
[13/ene./2021 23:42:14] [:] INFO - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@4eb4670c, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@2cff5253, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@3cd33c59, org.springframework.test.context.support.DirtiesContextTestExecutionListener@6b3d7b5, org.springframework.test.context.transaction.TransactionalTestExecutionListener@6b525c68, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@3de9f69b, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@187d248b, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@eb564e, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@79a3eb27, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@b0c97a6, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@7aa4a330]
java.lang.IllegalArgumentException: code must not be null
        at org.isf.ward.service.WardIoOperations.findWard(WardIoOperations.java:165)
        at org.isf.ward.service.WardIoOperations$$FastClassBySpringCGLIB$$cbff813d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:283)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)
        at org.isf.utils.db.OHServiceExceptionTranslator.translateSqlExceptionToOHServiceException(OHServiceExceptionTranslator.java:51)
        at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
        at org.isf.ward.service.WardIoOperations$$EnhancerBySpringCGLIB$$4a959184.findWard(<generated>)
        at org.isf.ward.test.Tests.lambda$testIoFindWardNull$0(Tests.java:233)
        at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
        at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
        at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
        at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
        at org.isf.ward.test.Tests.testIoFindWardNull(Tests.java:233)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
java.lang.IllegalArgumentException: code must not be null
        at org.isf.ward.service.WardIoOperations.findWard(WardIoOperations.java:165)
        at org.isf.ward.service.WardIoOperations$$FastClassBySpringCGLIB$$cbff813d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:283)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)
        at org.isf.utils.db.OHServiceExceptionTranslator.translateSqlExceptionToOHServiceException(OHServiceExceptionTranslator.java:51)
        at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672)
        at org.isf.ward.service.WardIoOperations$$EnhancerBySpringCGLIB$$4a959184.findWard(<generated>)
        at org.isf.ward.manager.WardBrowserManager.findWard(WardBrowserManager.java:268)
        at org.isf.ward.test.Tests.lambda$testMgrFindWardNull$3(Tests.java:383)
        at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
        at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
        at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
        at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
        at org.isf.ward.test.Tests.testMgrFindWardNull(Tests.java:383)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 46, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.707 sec
[13/ene./2021 23:42:16] [:] INFO - Closing org.springframework.context.support.GenericApplicationContext@45099dd3: startup date [Wed Jan 13 23:40:46 CET 2021]; root of context hierarchy
[13/ene./2021 23:42:16] [:] INFO - Closing JPA EntityManagerFactory for persistence unit 'default'
</details>

**Comment by dbmalkovsky** [comment]
The exception you found is caught by the test method correctly but the "traceback" still happens in the log; you will find the same issue in other packages like VaccineType for example.   I don't know how to suppress the printing of the runtime traceback.

**Comment by mwithi** [comment]
> The exception you found is caught by the test method correctly but the "traceback" still happens in the log; you will find the same issue in other packages like VaccineType for example. I don't know how to suppress the printing of the runtime traceback.

I remember something similar, but I didn't find it in VaccineType, rather in `TestPatientMergedEventListener`.

It is actually misleading having exceptions in the standard error > stdout when tests are successful, because you must remember it was intentional and flyover it, but it seems not avoidable... 

Maybe we can log something like "it should fail" along with it, in the stacktrace?

**Review by emecas — COMMENTED** [review]
I can see an exception as well at the end of the build , but no sure if it is part of the testing itself.

```
[20/Jan/2021 18:07:00] [:] INFO - Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@6e00de1e, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@90c3dcf, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@3507546, org.springframework.test.context.support.DirtiesContextTestExecutionListener@329a38ce, org.springframework.test.context.transaction.TransactionalTestExecutionListener@5a02e0ad, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@32084c67, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@3272e525, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@51cdf7ed, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@1c8762f1, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@6c1c6e72, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@49e2f519]
java.lang.IllegalArgumentException: code must not be null
        at org.isf.ward.service.WardIoOperations.findWard(WardIoOperations.java:165)
        at org.isf.ward.service.WardIoOperations$$FastClassBySpringCGLIB$$cbff813d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

```

On the other hand, because the number of tests , possibly this branch is not sync to develop branch like PR #291 ?

Results :

```
Tests run: 785, Failures: 0, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2021-01-20T18:07:01-05:00
[INFO] ------------------------------------------------------------------------ 
```

**Comment by mwithi** [comment]
> Maybe we can log something like "it should fail" along with it, in the stacktrace?

@dbmalkovsky +1

**Comment by dbmalkovsky** [comment]
IMHO, I don't see the advantage to adding logging to tests especially for a stacktrace.   Isn't the bottom line if the test passes then it make little or no difference if it also generates a stack trace.   There are other occurrences of generating a trace in other test suites.  This one just caught everyone's attention because it was at the end and near the totals.

**Comment by mwithi** [comment]
> IMHO, I don't see the advantage to adding logging to tests especially for a stacktrace. Isn't the bottom line if the test passes then it make little or no difference if it also generates a stack trace. There are other occurrences of generating a trace in other test suites. This one just caught everyone's attention because it was at the end and near the totals.

You mean that what matter is the final result? `Tests run: 785, Failures: 0, Errors: 0, Skipped: 1`

**Comment by dbmalkovsky** [comment]
Yes; if the stacktrace is important then it will show up as a `Failure`  in the summary totals.

**Pull request merged**
