### PR TITLE
Bump POI from 3.17 to 4.1.2

### PR DESCRIPTION
**Pull request by dbmalkovsky**
as found here https://community.jaspersoft.com/jasperreports-library/issues/13491
we bump to the latest known 100% working version with jasperreports-6.17.0

### CODE REVIEW

**Comment by mwithi** [comment]
I can see same results in https://github.com/informatici/openhospital-core/pull/298#issuecomment-764010825

**Comment by dbmalkovsky** [comment]
I just did the two versions of exporting to Excel and did the first 10 reports from "Launch Report" without any errors.   Are you sure your classpath doesn't have multiple versions of the jars?

**Comment by dbmalkovsky** [comment]
BTW, some of the reports could use improved formatting 😃

**Comment by mwithi** [comment]
> I just did the two versions of exporting to Excel and did the first 10 reports from "Launch Report" without any errors. Are you sure your classpath doesn't have multiple versions of the jars?

Do you mean also saving to Excel from PDF when using internal JasperViewer as viewer?
Statistics \ Any Report \ Launch Report \ Save to .xls (single or multiple sheet)

**Comment by dbmalkovsky** [comment]
Yes I mean that and from that and also from the Excel button directly:

image

**Comment by dbmalkovsky** [comment]
If you emptied your repository then the only difference left that I can currently think of is Windows vs. Linux?

**Comment by dbmalkovsky** [comment]
Looking at the class that you have in your traceback I see a change for the `getIndex()` method from returning a 'short` to an `int` on Dec 9, 2020:

<pre>
-    /**
-     * get the index within the HSSFWorkbook (sequence within the collection of Font objects)
-     * @return unique index number of the underlying record this Font represents (probably you don't care
-     *  unless you're comparing which one is which)
-     */
-
-    public short getIndex() { return (short)index; }
-
-    /**
-     * get the index within the HSSFWorkbook (sequence within the collection of Font objects)
-     * @return unique index number of the underlying record this Font represents (probably you don't care
-     *  unless you're comparing which one is which)
-     */
+    @Override
+    public int getIndex() { return index; }
</pre>

Apache POI 5.0.0 was released after that change on January 20, 2021.

So the fact that the method returning `short` is not found (by the traceback) indicates to me that you still have some mismatched jars/classes laying around in your classpath.

**Comment by mwithi** [comment]
> So the fact that the method returning short is not found (by the traceback) indicates to me that you still have some mismatched jars/classes laying around in your classpath.

the fact that `getIndex()S` is not found is correct, since I'm using 5.0.0, the question is why is still looking for it when in `net.sf.jasperreports.engine.export.JRXlsExporter.class` (note the return type expected is `int`) 🤔

image

**Pull request merged**
