### PR TITLE
OP-961: correct parsing of dates related to image

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-961

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
I don't understand the failures.   When I run locally using JDK 8 or JDK 11 in my IDE everything works fine.  When I use JDK 11 and run `mvn clean test` everything runs fine.

**Comment by mwithi** [comment]
> I don't understand the failures. When I run locally using JDK 8 or JDK 11 in my IDE everything works fine. When I use JDK 11 and run `mvn clean test` everything runs fine.
> 
> It also appears GitHub is having issues as the JDK 8 version is stuck building the code.

Looks like there is a problem with a Maven plugin https://github.com/informatici/openhospital-core/runs/8024838008?check_suite_focus=true#step:4:1519

**Comment by mwithi** [comment]
> I don't understand the failures. When I run locally using JDK 8 or JDK 11 in my IDE everything works fine. When I use JDK 11 and run `mvn clean test` everything runs fine.
> 
> It also appears GitHub is having issues as the JDK 8 version is stuck building the code.

Looks like there is a problem with a Maven plugin https://github.com/informatici/openhospital-core/runs/8024838008?check_suite_focus=true#step:4:1519

**Comment by dbmalkovsky** [comment]
Can you force a rebuild and see if things are better now (no more connection timeout)?; thanks

**Comment by mwithi** [comment]
> Can you force a rebuild and see if things are better now (no more connection timeout)?; thanks

Now there are 6 test failing (I suppose for something related to the timezone)
```
Failed tests:   
  testLoadDetails(org.isf.dicom.test.TestSqlDicomManager): (..)
  testLoadDetailsLongObject(org.isf.dicom.test.TestSqlDicomManager): (..)
  testLoadDetails(org.isf.dicom.test.TestFileSystemDicomManager): (..)
  testLoadDetailsLongObject(org.isf.dicom.test.TestFileSystemDicomManager): (..)
  testFileDicomGets(org.isf.dicom.test.Tests): (..)
  testFileDicomSets(org.isf.dicom.test.Tests): (..)
```

**Review by mwithi — APPROVED** [review]
Seems fine now and ok for me. Thansk !

**Pull request merged**
